config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    post "/like", to:"likes#like_toggle", defaults: { format: 'js' }
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
    collection do
      get :search, defaults: { format: 'js' }
      get :search_post, defaults: { format: 'js' }
      get :crop
    end
    member do
      get :autoinit, defaults: { format: 'js' }
      get :cancel, defaults: { format: 'js' }
      get :by_song
    end
  end
  resources :timelines, only: [:index] do
    collection do
      get :saves
    end
    member do
      get :profile
      get :subscribe
    end
  end
  resources :follows, only: [:create] do
    member do
      post :toggle, defaults: { format: 'js' }
    end
  end
  resources :alarms, only: [:index]
  resources :alarms, only: [:destroy], defaults: { format: 'js' }
  resources :subcomments, only: [:create, :destroy], defaults: { format: 'js' }

  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/copyurl/:id' => 'copys#copy', defaults: { format: 'js' }, :as => '/copyurl'
  get '/timelines/tag/:name' => 'timelines#tag'
  get '/check_identity/:identity' => 'checks#identity'
  get '/check_name/:name' => 'checks#name'
  get '/direct_music_search/:search_music' => 'posts#music_search'
  get '/direct_search_songs/:search_song' => 'posts#direct_search_songs'
  get '/direct_search_singers/:search_singer' => 'posts#direct_search_singers'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  after_create :generate_alarm
  serialize :content, JSON

  #유저 태그 기능
  after_create do
    hashtags = self.content.scan(/@\w+/)
    hashtags.uniq.map do |hashtag|
      if User.find_by(name: hashtag.delete('@')).present?
        user = User.find_by(name: hashtag.delete('@'))
        tag = Tag.find_by(name: hashtag.delete('@'),
                          user_id: user.id,
                          comment_id: self.id)
        if tag.nil?
          Tag.create(name: hashtag.delete('@'),
                     user_id: user.id,
                     comment_id: self.id)
        else
          tag.update(name: hashtag.delete('@'),
                     user_id: user.id,
                     comment_id: self.id)
        end
      end
    end
  end

  belongs_to :user
  belongs_to :post

  has_many :tags
  has_many :subcomments, dependent: :destroy

  def generate_alarm
    if self.post.user != self.user
      if self.post.user.comment_on == true
        Alarm.create(user_id: self.post.user.id, content: self.user.name, findable_id: self.post.id, is_read: false, alarm_type: "comment")
      end
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_ownership!, only: [:destroy]

    def create
        @new_comment = Comment.new(set_comment_params)
        @new_comment.content
        @new_comment.user_id = current_user.id
        @new_comment.post_id = params[:post_id]
        respond_to do |format|
            if @new_comment.save
                @post = @new_comment.post
                format.js
                length2 = Comment.last.id
                Comment.find(length2).update(is_first?: false)
            else
                format.html{ redirect_to :back,
                             notice: "오류가 발생했습니다." }
            end
        end
    end

    def destroy
        @comment.destroy

        respond_to do |format|
          format.js
        end
    end

    private
    def check_ownership!
        @comment = Comment.find_by(id: params[:id])
        redirect_to root_path if current_user.id != @comment.user.id
    end

    def set_comment_params
        params.require(:comment).permit(:content,:image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def render_with_hashtags(content)
    content.gsub(/@\w+/){|word| link_to word, "/timelines/tag/#{word.delete('@')}", class: "chip"}.html_safe
  end
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
  <div id="showCommentProfile">
    <div>
      <% if comment.user.thumbnail.present? %>
        <%= image_tag(comment.user.thumbnail, id: "showImageComment") %>
      <% else %>
        <img src="/people.jpg" id="showImageComment">
      <% end %>
    </div>
    <div id="showCommentStyle">
      <div id="showCommentName">
        <%= link_to "#{comment.user.name}", profile_timeline_path(comment.user), class: "black-text" %>
      </div>
      <div id="showCommenttime">
        <%= time_ago_in_words comment.created_at %> 전<br>
        <% if user_signed_in? && comment.user.id == current_user.id %>
          <%= link_to '삭제', post_comment_path(@post, comment), method: :delete, class: "onefive", id: "delete-margin", remote: true %>
        <% end %>
          <%= link_to "대댓글(#{comment.subcomments.size})", "#", class: "onefive add-margin", id: "#{comment.id}-subcomment-gen1", remote: true %>
      </div>
    </div>
  </div>
  <div id="showCommentContent" class="pre-line">
    <%= render_with_hashtags(comment.content) %>
  </div>
  <div><hr id="showLine3"/></div>

  <% if comment.subcomments.present? %>
    <div id="<%= comment.id %>-subcomments" style=display:none;>
      <div id="postsubcomments-<%= comment.id %>">
        <% comment.subcomments.each do |subcomment| %>
          <%= render subcomment %>
        <% end %>
      </div>

      <div id="showCommentWrite">
        <div>
          <% if user_signed_in? && current_user.thumbnail.present? %>
            <i class="material-icons grey-text">subdirectory_arrow_right</i><%= image_tag(current_user.thumbnail, id: "subcommentImage") %>
          <% else %>
            <i class="material-icons grey-text">subdirectory_arrow_right</i><img src="/people.jpg" id="subcommentImage">
          <% end %>
        </div>
        <!--  대댓글작성기능 -->
        <%= form_for(@subcomment, url: subcomments_path, remote: true) do |f| %>
          <div class="input-field">
            <%= f.text_area :content, class: "SubommentTextarea #{comment.id}-sub", placeholder: "대댓글쓰기...", required: true, id: "subcomment-content-#{comment.id}" %>
            <%= f.hidden_field :post_id, value: "#{comment.post.id}" %>
            <%= f.hidden_field :comment_id, value: "#{comment.id}" %>
          </div>
          <div class="input-field">
            <%= f.submit "대댓글 쓰기", class: "btn indigo darken-4 right" %>
          </div>
        <% end %>
      </div>
    </div>
  <% elsif comment.subcomments.empty? == true && comment.is_first? == false %>
    <div id="<%= comment.id %>-subcomments" style=display:none;>
      <div id="postsubcomments-<%= comment.id %>">
      </div>
      <!--  대댓글작성기능 -->
      <div id="showCommentWrite">
        <div>
          <% if user_signed_in? && current_user.thumbnail.present? %>
            <i class="material-icons grey-text">subdirectory_arrow_right</i><%= image_tag(current_user.thumbnail, id: "subcommentImage") %>
          <% else %>
            <i class="material-icons grey-text">subdirectory_arrow_right</i><img src="/people.jpg" id="subcommentImage">
          <% end %>
        </div>
        <%= form_for(@subcomment, url: subcomments_path, remote: true) do |f| %>
          <div class="input-field">
            <%= f.text_area :content, class: "SubommentTextarea #{comment.id}-sub", placeholder: "대댓글쓰기...", required: true, id: "subcomment-content-#{comment.id}" %>
            <%= f.hidden_field :post_id, value: "#{comment.post.id}" %>
            <%= f.hidden_field :comment_id, value: "#{comment.id}" %>
          </div>
          <div class="input-field">
            <%= f.submit "대댓글 쓰기", class: "btn indigo darken-4 right", id: "mceu_31" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<script>
$("#<%= comment.id %>-subcomment-gen1").on("click", function(){
  $("#<%= comment.id %>-subcomments").toggle();
});

$(document).ready(function(){
  var clipboard = new Clipboard('.clipboard-btn');
});

$('.SubommentTextarea.<%= comment.id %>-sub').keypress(function (e) {
 var key = e.which;
 if(key == 13 && !e.shiftKey)  // the enter key code
  {
    $('input').click();
    $('#comment_content').val('');
    // e.preventDefault();
    return false;
  }
});
</script>

<style>
#subcommentImage {
  width: 40px;
  height: 40px;
}

.SubommentTextarea {
  margin-left: 20px;
  margin-top: 1rem;
  resize: none;
  border: 1px solid #7a7a7a;
  padding: 10px 20px 10px 20px;
  width: 493px !important;
  height: 70px !important;
  outline: none;
}

.add-margin {
  margin-left: 480px;
}
</style>

app/views/comments/create.js.erb
$('#comment_content').val("");
$('#comment-size').text("<%= @post.comments.size + @post.subcomments.size %>");
$('#postcomment').append("<%= j(render(@new_comment)) %>");

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();
$('#comment-size').text("<%= @comment.post.comments.size + @comment.post.subcomments.size %>");