config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    post "/like", to:"likes#like_toggle", defaults: { format: 'js' }
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
    collection do
      get :search, defaults: { format: 'js' }
      get :search_post, defaults: { format: 'js' }
      get :crop
    end
    member do
      get :autoinit, defaults: { format: 'js' }
      get :cancel, defaults: { format: 'js' }
      get :by_song
    end
  end
  resources :timelines, only: [:index] do
    collection do
      get :saves
    end
    member do
      get :profile
      get :subscribe
    end
  end
  resources :follows, only: [:create] do
    member do
      post :toggle, defaults: { format: 'js' }
    end
  end
  resources :alarms, only: [:index]
  resources :alarms, only: [:destroy], defaults: { format: 'js' }
  resources :subcomments, only: [:create, :destroy], defaults: { format: 'js' }

  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/copyurl/:id' => 'copys#copy', defaults: { format: 'js' }, :as => '/copyurl'
  get '/timelines/tag/:name' => 'timelines#tag'
  get '/check_identity/:identity' => 'checks#identity'
  get '/check_name/:name' => 'checks#name'
  get '/direct_music_search/:search_music' => 'posts#music_search'
  get '/direct_search_songs/:search_song' => 'posts#direct_search_songs'
  get '/direct_search_singers/:search_singer' => 'posts#direct_search_singers'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  #댓글
  has_many :comments

  #대댓글
  has_many :subcomments

  #좋아요
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  mount_uploader :image, PostImageUploader
  mount_uploaders :post_images, EditerUploader

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_image

  serialize :post_images, JSON # if we user sqlite3
  serialize :song_ids, Array # if we user sqlite3

  def self.search(query)
      self.where("title || content LIKE ?","%#{query}%")
  end

  def include_song?(params)
    self.song_ids.map do |song_id|
      if song_id == params
        return true
      end
    end

    return false
  end

  def crop_image
    image.recreate_versions! if crop_x.present?
  end
end

app/models/singer.rb
class Singer < ActiveRecord::Base
  has_many :songs

  def self.generate_singers
    (143179..143250).each do |i|
      # begin
        result = Wombat.crawl do
          base_url "https://music.naver.com/"
          path "/artist/track.nhn?artistId=" + "#{i}" + "&sorting=popular"
            music_singers({ css: ".tb_artist"  }, :list)
              features css: '.nav-item-opensource'
              business css: '.nav-item-business'
        end

        if result.present?
          result["music_singers"].each_with_index do |s, index|
            if Singer.find_by(name: s).nil?
              Singer.find_or_create_by(name: s)
              puts "#{i} 크롤링 함 : #{s}"

            end
          end
        end
      # rescue
      #   puts "stop #{i}"
      #   next
      # end
    end

  end

  def self.search(query)
      self.where("name LIKE ?","%#{query}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_ownership!, only: [:edit, :update, :destroy]

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
    elsif params[:search_user]
      @posts = User.search(params[:search_user]).find_posts.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
    else
      @posts = Post.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
    end
    @musics = Song.all.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @post = Post.new
  end

  def search
    if params[:search_music]
      @musics = Song.search(params[:search_music]).paginate(:page => params[:page], :per_page => 100)
      @check_params = params[:search_music]
    elsif params[:search_singer]
      @musics = Song.find_songs(Singer.search(params[:search_singer])).paginate(:page => params[:page], :per_page => 100)
    end

    respond_to do |format|
      format.js
    end
  end

  def search_post
    if params[:search_music]
      songs = Song.search(params[:search_music])
      singers = Song.find_songs(Singer.search(params[:search_music]))
      @musics = songs + singers

      respond_to do |format|
        format.js
      end
    end
  end

  def music_search
    if params[:search_music]
      songs = Song.search(params[:search_music])
      singers = Song.find_songs(Singer.search(params[:search_music]))
      @musics = songs + singers

      respond_to do |format|
        format.js
      end
    end
  end

  def direct_search_songs
    if params[:search_song]
      @musics = Song.search(params[:search_song])
    end

    respond_to do |format|
      format.js
    end
  end

  def direct_search_singers
    if params[:search_singer]
      @musics = Song.find_songs(Singer.search(params[:search_singer]))
    end

    respond_to do |format|
      format.js
    end
  end

  def by_song
    post_ids = []
    Post.all.each do |p|
      post_ids << p.id if p.include_song?(params[:id]) == true
    end

    @posts = Post.where(id: post_ids).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  def autoinit
    @music = Song.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def cancel
    @music = Song.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    if params[:post][:title] == ""
      redirect_to :back, notice: "제목은 필수 입력 항목입니다."
    elsif params[:post][:subtitle] == ""
      redirect_to :back, notice: "부제목은 필수 입력 항목입니다."
    elsif params[:post][:content] == ""
      redirect_to :back, notice: "내용은 필수 입력 항목입니다."
    elsif params[:post][:song_ids] == nil
      redirect_to :back, notice: "음악은 꼭 넣으셔야 합니다."
    else
      @post = Post.new(set_params)
      @post.user_id = current_user.id
      respond_to do |format|
        if @post.save
          if params[:post][:image].present?
            format.html{ render :crop }
          end
        format.html{ redirect_to post_path(@post),
                    notice: "게시물이 성공적으로 작성되었습니다."}
        else
          format.html{ render :new,
                      notice: "오류가 발생했습니다."}
        end
      end
    end
  end

  def crop
    @post = Post.new
  end

  def show
    @comment = Comment.new
    @subcomment = Subcomment.new
    @post.view_count += 1
    @post.save
    @user = @post.user

    if params[:page]
      @comments = @post.comments.paginate(:page => params[:page], :per_page => 10)
    else
      last_page = @post.comments.paginate(:page => params[:page], :per_page => 10).total_pages
      @comments = @post.comments.paginate(:page => last_page, :per_page => 10)
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update(set_params)
        if params[:post][:image].present?
          render :crop
        else
          format.html{redirect_to post_path(@post),
                      notice: "게시물이 성공적으로 저장되었습니다."}
        end
      else
        format.html{render :edit,
                    notice: "오류가 발생했습니다."}
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html{redirect_to root_path, notice: "게시물이 성공적으로 삭제되었습니다."}
    end
  end

  private
  def set_params
    params.require(:post).permit(:title, :subtitle, :content, :image, :crop_x, :crop_y, :crop_w, :crop_h, song_ids: [], post_images: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def check_ownership!
    redirect_to root_path if @post.user.id != current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(content)
    content.scan(/@\w+/).map do |c|
      if User.find_by(name: c.delete('@')).nil?
        return content
      end
    end

    content.gsub(/@\w+/){|word| link_to word, "/timelines/tag/#{word.delete('@')}", class: "chip"}.html_safe
  end
end

app/views/posts/_buttons.html.erb
<!-- 저장 기능 -->
    <span id='like_toggle'>
      <% if user_signed_in? && current_user.is_like?(@post) %>
          <%= link_to 'bookmark', post_like_path(@post), method: :post, class: "material-icons right black-text", id: "like_default", remote: true %>
      <% else %>
          <%= link_to 'bookmark_border', post_like_path(@post), method: :post, class: "material-icons right black-text", id: "like_default" ,remote: true%>
      <% end %>
    </span>
    <p id="like_size"><%= @post.likes.size %></p>
<!-- 댓글 수 -->
    <i class="material-icons right">sms</i><p id="comment-size"><%= @post.comments.size + Subcomment.where(post_id: @post.id).size %></p>
<!-- 링크 복사 기능 -->
    <a href="<%= copyurl_path(@post) %>" class="clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#copy-<%= @post.id %>" data-remote="true" onclick="M.toast({html: '링크가 복사되었습니다.'})"><i class="material-icons right black-text">share</i></a>

app/views/posts/_form.html.erb
<div style="margin-top: 80px;">
  <div class="side_empty">
    <%= form_for @post do |f| %>

      <div class="field form_title">
        <%= f.text_field :title, placeholder: "제목을 입력하세요.", class: "input-xlarge newPostForm", autocomplete: "off" %>
      </div>

      <div class="field form_subtitle">
        <%= f.text_area :subtitle, placeholder: "부제를 입력하세요.",class: "newPostFormSub", autocomplete: "off" %>
      </div><br>

      <div id="field_control_img">
        <div class="field form_songtitle">
          <a href="#modal" class="modal-trigger btn white indigo-text text-darken-4">음악 불러오기</a>
          <div id="music-result">
          </div>
        </div>
        <div class="field field_control">
          <%= f.file_field :image, id: "hidden_file_field" %>
          <%= link_to 'image', '#', class: "large material-icons black-text", id: "hidden_file_field_trigger" %>
          <span id="added_file-result"></span>
        </div>
      </div>

      <div class="field hiphop">
        <%= f.text_area :content, class: "tinymce", placeholder: '모든 칸을 채우지 않은 채 제출하면 전부 날아갈 수 있어요 ㅇ.<' %>
        <%= tinymce %>
      </div><br>

      <div class="input-field">
        <%= f.submit '작성', class: "btn indigo darken-4" %>
        <%= link_to '그만 쓸래요', posts_path, class: "btn indigo darken-4" %>
      </div>

    <% end %>

  </div>
</div>

<div id="modal" class="modal">
 <div id="search123">
  <div id="search5"> <!--두번째 세션 탭 시작 -->
     <ul id ="search_hover" class="tabs">
       <li class="tab session_active"><a class="active grey-text" href="#search_title" id="search-title">제목</a></li>
       <li class="tab session1_li grey-text bigfont">|</li>
       <li class="tab session_active"><a class="active grey-text" href="#search_singer" id="search-singer">가수</a></a></li>
     </ul>
  </div> <!-- 탭 끝 -->
  <div id="search3"> <!-- 세번째 세션시작. 검색목록 나열 -->
    <div id="search_title"> <!-- 제목을 눌렀을 때 -->
      <div id=#search4> <!-- 첫번째 세션 -->
        <%= form_tag(search_posts_path, method: :get, remote: true) do %>
          <div class="search_input search_input_search2"> <!--아이콘과 검색바 -->
            <!--아이콘-->
            <i class="material-icons search_icon">search</i>
            <!--검색-->
            <div class="search_input_div"><input type="text" name="search_music" id="search_song"></div>
          </div>
        <% end %>
        <div><br><br>
          <div id="search_music_article">
            <ol id="music-lists">
            </ol>
            <%#= will_paginate %>
          </div>
        </div>
      </div> <!-- 첫 세션끝 -->
    </div> <!-- 음악을 눌렀을 때 끝 -->
        <!-- 성원형. 위에 search_music 아이디를 반복해주면 됩니다.-->
   <div id="search_singer"> <!-- 사용자를 눌렀을때 -->
     <div id=#search4> <!-- 첫번째 세션 -->
       <%= form_tag(search_posts_path, method: :get, remote: true) do %>
         <div class="search_input search_input_search2"> <!--아이콘과 검색바 -->
           <!--아이콘-->
           <i class="material-icons search_icon">search</i>
           <!--검색-->
           <div class="search_input_div"><input type="text" name="search_singer" id="search_singer"></div>
         </div>
       <% end %>
       <div><br><br>
         <div id="search_music_article">
           <ol id="music-lists2">
           </ol>
         </div>
       </div>
     </div> <!-- 첫 세션끝 -->
   </div> <!-- 첫 세션끝 -->
   </div> <!-- 사용자를 눌렀을때 끝 -->
  </div> <!--세번째 세션 끝 -->
 </div>
</div>

<script>
  $(document).ready(function(){
    $('.modal').modal();
  });
  $('#search-title').on('click', function () {
      $(this).attr('style', 'color: #0b1d7b !important');
      $('#search-singer').attr('style', 'color: #7a7a7a !important');
  });
  $('#search-singer').on('click', function () {
    $(this).attr('style', 'color: #0b1d7b !important');
    $('#search-title').attr('style', 'color: #7a7a7a !important');
  });

  function search_songs(search_song){
    $.get("/direct_search_songs/" + search_song, function(){
      console.log('dd');
    });
  }

  function search_singers(search_singer){
    $.get("/direct_search_singers/" + search_singer, function(){
      console.log('pp');
    });
  }

  $('input#search_song').on('keyup', function(){
    var val = this.value;
    search_songs(val);
  });

  $('input#search_singer').on('keyup', function(){
    var val = this.value;
    search_singers(val);
  });
</script>

<style>
  .cropit-preview {
    position: relative;
    width: 300px;
    height: 180px;
  }
  .cropit-preview-image-container {
    cursor: move;
  }
</style>
<script>
$(document).ready(function(){
  $('.sidenav').sidenav({
    edge: 'right'
  });
});
$(document).ready(function(){
  $('.modal').modal();
});
$(document).ready(function(){
  $('.tabs').tabs();
});

$('#search-music').on('click', function () {
  $(this).attr('style', 'color: #0b1d7b !important');
  $('#search-user').attr('style', 'color: #7a7a7a !important');
  $('#search-post').attr('style', 'color: #7a7a7a !important');
});
$('#search-user').on('click', function () {
  $(this).attr('style', 'color: #0b1d7b !important');
  $('#search-music').attr('style', 'color: #7a7a7a !important');
  $('#search-post').attr('style', 'color: #7a7a7a !important');
});
$('#search-post').on('click', function () {
  $(this).attr('style', 'color: #0b1d7b !important');
  $('#search-music').attr('style', 'color: #7a7a7a !important');
  $('#search-user').attr('style', 'color: #7a7a7a !important');
});

$('#hidden_file_field_trigger').on('click', function(){
  $('#hidden_file_field').trigger('click');
});

$('#hidden_file_field').on('change', function(){
  var url = $(this).val();
  $('#added_file-result').empty();
  $('#added_file-result').append(url);
})
</script>

app/views/posts/_posts.html.erb
<% @posts.each do |p| %>
  <div class="p_content">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="card_all">
            <div class="card_img">
              <% if p.image.present? %>
                <%= image_tag p.image_url(:thumb), width: 150, height: 150 %>
              <% else %>
                <img src="/default.jpg" width="150" height="150">
              <% end %>
            </div>
            <div class="card_flex">
              <div class="card_top">
                <% if p.user == current_user %>
                  <a class="dropdown-trigger" data-target="dropdown2">
                    <i class="tiny material-icons onefive" style="float: right;">more_horiz</i>
                  </a>
                  <ul id="dropdown2" class="dropdown-content">
                    <li><a href="<%= edit_post_path(p) %>" id="onefive">수정</a></li>
                    <li class="divider" tabindex="-1"></li>
                    <li><a href="<%= post_path(p) %>" id="onefive" data-method="delete">삭제</a></li>
                  </ul>
                <% end %>
              </div>
              <div class="content_title">
                <%= link_to "#{p.title.truncate(14)}", post_path(p), class: "onefive" %>
              </div>
              <div class="content_song">
                <% if p.song_ids.present? %>
                <div class="content_song_icon"><i class="material-icons">album</i></div>
                    <%= Song.find(p.song_ids.first.to_i).title.truncate(18) %> - <%= Song.find(p.song_ids.first.to_i).singer.name %>
                  <% if p.song_ids.size > 2 %>
                    외 <%= p.song_ids.size - 1 %>곡
                  <% end %>
                <% end %>
              </div>
              <div class="content_subtitle">
                <%= truncate(p.subtitle, :ommision => "...", :length => 50) %>
              </div>
              <div class="content_preview">
                <%= truncate_html(p.content, length: 160, omission: '...') %>
              </div>
            </div>
            </div>
          </div>
          <div class="card-action">
            <div class="things things_flex">
              <div class="things_comment">
                <i class="tiny material-icons onefive">comment</i>
              </div>
              <div class="things_commentcount">
                <%= p.comments.size + p.subcomments.size %>
              </div>
              <div class="things_favorite">
                <% if p.liked_users.include?(current_user) %>
                  <i class="tiny material-icons onefive">bookmark</i>
                <% else %>
                  <i class="tiny material-icons onefive">bookmark_border</i>
                <% end %>
              </div>
              <div class="things_favoritecount">
                <%= p.likes.size %>
              </div>
              <span class="things_text">
                <%= time_ago_in_words p.created_at %> 전 · <a href="<%= profile_timeline_path(p.user) %>" id="card-align"><%= p.user.name %></a> 씀
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/autoinit.js.erb
$('#music-result').append('<p class="musicSearchCenterNew" id="music-<%= @music.id %>">'+'<%= image_tag(@music.image) %>' + '<%= @music.title %>' +' | '+ '<%= @music.album %>' + ' | ' + '<%= link_to "취소", cancel_post_path(@music), remote: true, class: :onefive %>' + '<br>' +
                          '<input type="hidden" name="post[song_ids][]" value="<%= @music.id %>"/>' + '</p>');

app/views/posts/by_song.html.erb
<div id="posts">
  <%= render partial: "posts" %>
</div>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

<!--글 쓰기 버튼-->
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large" href="<%= new_post_path %>">
      <i class="large material-icons">mode_edit</i>
    </a>
  </div>
<!--//-->

<style>
.loginandsignup>ul,li {
  display:inline;
        }
p iframe {
  display: none;
}
p img {
  display: none;
}
</style>

app/views/posts/cancel.js.erb
$('#music-<%= @music.id %>').remove();

app/views/posts/crop.html.erb
<div class='row container'>
  <div class='col s8'>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h5 class="panel-title onefive">대표이미지 사이즈를 알맞게 조절해주세요</h5>
      </div>
      <div class="panel-body">
        <%= image_tag @post.image_url(:large), id: "cropbox" %>
        <br>
        <%= form_for(@post) do |f| %>
          <% %w[x y w h].each do |attribute| %>
            <%= f.hidden_field "crop_#{attribute}" %>
          <% end %>

          <div class="form-actions">
            <%= f.submit '저장', class: "btn indigo darken-4 white-text" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class='col s4'>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h5 class="panel-title onefive">미리보기</h5>
      </div>
      <div class="panel-body">
        <div style="width: 100px; height: 100px; overflow:hidden">
          <%= image_tag @post.image.url(:large), id: "preview" %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
var AvatarCrop,
bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

$(function() {
  return new AvatarCrop();
});

AvatarCrop = (function() {
  function AvatarCrop() {
    this.updatePreview = bind(this.updatePreview, this);
    this.update = bind(this.update, this);
    var height, width;
    width = parseInt($('#cropbox').width());
    height = parseInt($('#cropbox').height());
    $('#cropbox').Jcrop({
      aspectRatio: 1,
      setSelect: [0, 0, width, height],
      onSelect: this.update,
      onChange: this.update
    });
  }

  AvatarCrop.prototype.update = function(coords) {
    $('#post_crop_x').val(coords.x);
    $('#post_crop_y').val(coords.y);
    $('#post_crop_w').val(coords.w);
    $('#post_crop_h').val(coords.h);
    return this.updatePreview(coords);
  };

  AvatarCrop.prototype.updatePreview = function(coords) {
    var rx, ry;
    rx = 100 / coords.w;
    ry = 100 / coords.h;
    return $('#preview').css({
      width: Math.round(rx * $('#cropbox').width()) + 'px',
      height: Math.round(ry * $('#cropbox').height()) + 'px',
      marginLeft: '-' + Math.round(rx * coords.x) + 'px',
      marginTop: '-' + Math.round(ry * coords.y) + 'px'
    });
  };

  return AvatarCrop;

})();
</script>

app/views/posts/direct_search_songs.js.erb
$('#music-lists').empty();
$('#music-lists').append('<% if @musics.present? %>'+
                           '<% @musics[0..100].each do |music| %>'+
                           '<li>' + '<%= image_tag(music.image) %> ' + '<%= link_to "#{music.title}", autoinit_post_path(music), class: "onefive", remote: true %> ' + '| <%= music.singer.name %> ' + '| <%= music.album %>'+ '</li>' + '<br>' +
                           '<% end %>'+
                         '<% end %>');

app/views/posts/edit.html.erb
<%= render partial: "form" %>

app/views/posts/index.html.erb
<% if user_signed_in? && current_user.alarms.present? %>
  <script type="text/javascript">
    var toastHTML= "읽지 않은 알람이 있습니다."
    M.toast({html: toastHTML});
  </script>
<% end %>


<div id="posts">
  <%= render partial: "posts" %>
</div>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

<!--글 쓰기 버튼-->
  <div class="fixed-action-btn">
    <a class="btn-floating btn-large" href="<%= new_post_path %>">
      <i class="large material-icons">mode_edit</i>
    </a>
  </div>
<!--//-->

<style>
.loginandsignup>ul,li {
  display:inline;
        }
p iframe {
  display: none;
}
p img {
  display: none;
}
</style>

app/views/posts/music_search.js.erb
$('#music-lists3').empty();
$('#music-lists3').append('<% if @musics.present? %>'+
                        '<% @musics[0..100].each do |m| %>'+
                          '<div id="search_music_img">'+'<%= image_tag(m.image, height: '50', width: '50') %>'+'</div>'+
                          '<div id="search_music_article">'+
                            '<div class="music_item1">'+'<%= link_to "#{m.title}", by_song_post_path(m), class: "search_music_title" %>'+'</div>'+
                            '<div class="search_music_item music-item2">'+'<%= m.singer.name %>'+'</div>'+
                            '<div class="search_music_item music-item3">'+'['+'<%= m.album %>'+']'+'</div>'+
                          '</div>'+
                          '<div><hr id="search_hrTag"/> <!-- 구분선 --></div>'+
                         '<% end %>'+
                      '<% end %>');

app/views/posts/new.html.erb
<div class="container">
  <%= render partial: "form" %>
</div>

app/views/posts/search.js.erb
<% if @check_params.present? %>
$('#music-lists').empty();
$('#music-lists').append('<% @musics[0..100].each do |music| %>'+
                         '<li>' + '<%= image_tag(music.image) %> ' + '<%= link_to "#{music.title}", autoinit_post_path(music), class: "onefive", remote: true %> ' + '| <%= music.singer.name %> ' + '| <%= music.album %>'+ '</li>' + '<br>' +
                         '<% end %>');
<% else %>
$('#music-lists2').empty();
$('#music-lists2').append('<% @musics[0..100].each do |music| %>'+
                        '<li>' + '<%= image_tag(music.image) %> ' + '<%= link_to "#{music.title}", autoinit_post_path(music), class: "onefive", remote: true %> ' + '| <%= music.singer.name %> ' + '| <%= music.album %>'+ '</li>' + '<br>' +
                        '<% end %>');
<% end %>

app/views/posts/search_post.js.erb
$('#music-lists3').empty();
$('#music-lists3').append('<% @musics[0..100].each do |m| %>'+
                          '<div id="search_music_img">'+'<%= image_tag(m.image, height: '80', width: '80') %>'+'</div>'+
                          '<div id="search_music_article">'+
                            '<div class="music_item1">'+'<%= link_to "#{m.title}", by_song_post_path(m), class: "search_music_title" %>'+'</div>'+
                            '<div class="search_music_item music-item2">'+'<%= m.singer.name %>'+'</div>'+
                            '<div class="search_music_item music-item3">'+'['+'<%= m.album %>'+']'+'</div>'+
                          '</div>'+
                          '<div><hr id="search_hrTag"/> <!-- 구분선 --></div>'+
                         '<% end %>');