config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    post "/like", to:"likes#like_toggle", defaults: { format: 'js' }
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
    collection do
      get :search, defaults: { format: 'js' }
      get :search_post, defaults: { format: 'js' }
      get :crop
    end
    member do
      get :autoinit, defaults: { format: 'js' }
      get :cancel, defaults: { format: 'js' }
      get :by_song
    end
  end
  resources :timelines, only: [:index] do
    collection do
      get :saves
    end
    member do
      get :profile
      get :subscribe
    end
  end
  resources :follows, only: [:create] do
    member do
      post :toggle, defaults: { format: 'js' }
    end
  end
  resources :alarms, only: [:index]
  resources :alarms, only: [:destroy], defaults: { format: 'js' }
  resources :subcomments, only: [:create, :destroy], defaults: { format: 'js' }

  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/copyurl/:id' => 'copys#copy', defaults: { format: 'js' }, :as => '/copyurl'
  get '/timelines/tag/:name' => 'timelines#tag'
  get '/check_identity/:identity' => 'checks#identity'
  get '/check_name/:name' => 'checks#name'
  get '/direct_music_search/:search_music' => 'posts#music_search'
  get '/direct_search_songs/:search_song' => 'posts#direct_search_songs'
  get '/direct_search_singers/:search_singer' => 'posts#direct_search_singers'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/singer.rb
class Singer < ActiveRecord::Base
  has_many :songs

  def self.generate_singers
    (143179..143250).each do |i|
      # begin
        result = Wombat.crawl do
          base_url "https://music.naver.com/"
          path "/artist/track.nhn?artistId=" + "#{i}" + "&sorting=popular"
            music_singers({ css: ".tb_artist"  }, :list)
              features css: '.nav-item-opensource'
              business css: '.nav-item-business'
        end

        if result.present?
          result["music_singers"].each_with_index do |s, index|
            if Singer.find_by(name: s).nil?
              Singer.find_or_create_by(name: s)
              puts "#{i} 크롤링 함 : #{s}"

            end
          end
        end
      # rescue
      #   puts "stop #{i}"
      #   next
      # end
    end

  end

  def self.search(query)
      self.where("name LIKE ?","%#{query}%")
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_timeline, only: [:profile, :subscribe]

  def index
    @posts = Post.where(user_id: current_user.followings.ids).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  def profile
  end

  def subscribe
  end

  def saves
    @posts = current_user.liked_posts.order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  def tag
    tag = Tag.find_by(name: params[:name])
    @user = User.find(tag.user_id)
    @posts = Post.where(user_id: @user.id).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end

  private
  def set_timeline
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).order(created_at: :desc).paginate(:page => params[:page], :per_page => 3)
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_posts.html.erb
<% @posts.each do |p| %>
  <div class="p_content">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="card_all">
            <div class="card_img">
              <% if p.image.present? %>
                <%= image_tag p.image_url(:thumb), width: 150, height: 150 %>
              <% else %>
                <img src="/default.jpg" width="150px" height="150px">
              <% end %>
            </div>
            <div class="card_flex">
              <div class="card_top">
                <% if p.user == current_user %>
                  <a class="dropdown-trigger" data-target="dropdown2">
                    <i class="tiny material-icons onefive" style="float: right;">more_horiz</i>
                  </a>
                  <ul id="dropdown2" class="dropdown-content">
                    <li><a href="<%= edit_post_path(p) %>" id="onefive">수정</a></li>
                    <li class="divider" tabindex="-1"></li>
                    <li><a href="<%= post_path(p) %>" id="onefive" data-method="delete">삭제</a></li>
                  </ul>
                <% end %>
              </div>
              <div class="content_title">
                <%= link_to "#{p.title.truncate(14)}", post_path(p), class: "onefive" %>
              </div>
              <div class="content_song">
                <% if p.song_ids.present? %>
                <div class="content_song_icon"><i class="material-icons">album</i></div>
                    <%= Song.find(p.song_ids.first.to_i).title.truncate(18) %> - <%= Song.find(p.song_ids.first.to_i).singer.name %>
                  <% if p.song_ids.size > 2 %>
                    외 <%= p.song_ids.size - 1 %>곡
                  <% end %>
                <% end %>
              </div>
              <div class="content_subtitle">
                <%= truncate(p.subtitle, :ommision => "...", :length => 50) %>
              </div>
              <div class="content_preview">
                <%= truncate_html(p.content, length: 160, omission: '...') %>
              </div>
            </div>
            </div>
          </div>
          <div class="card-action">
            <div class="things things_flex">
              <div class="things_comment">
                <i class="tiny material-icons onefive">comment</i>
              </div>
              <div class="things_commentcount">
                <%= p.comments.size + p.subcomments.size %>
              </div>
              <div class="things_favorite">
                <% if p.liked_users.include?(current_user) %>
                  <i class="tiny material-icons onefive">bookmark</i>
                <% else %>
                  <i class="tiny material-icons onefive">bookmark_border</i>
                <% end %>
              </div>
              <div class="things_favoritecount">
                <%= p.likes.size %>
              </div>
              <span class="things_text">
                <%= time_ago_in_words p.created_at %> 전 · <a href="<%= profile_timeline_path(p.user) %>" id="card-align"><%= p.user.name %></a> 씀
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/timelines/index.html.erb
<% if @posts.present? %>
  <div id="posts">
    <%= render partial: "posts" %>
  </div>
<% else %>
  <h5 class="grey-text center">아직 구독중인 사람이 없습니다.</h5>
<% end %>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

<style>
p iframe {
  display: none;
}
p img {
  display: none;
}
</style>

app/views/timelines/index.js.erb
$('#posts').append('<%= j render partial: "posts" %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/timelines/profile.html.erb
<div class="profileimage center">
    <% if @user.thumbnail.present? %>
      <%= link_to image_tag(@user.thumbnail, class: "z-depth-3 circle tl-size"), profile_timeline_path(@user.id) %>
    <% else %>
      <img src="/people.jpg" class="tl-size circle">
    <% end %>
</div>

<div class="user_name">
  <%= @user.name %>
</div>

<div class="user_subscribe">
  <a href="<%= subscribe_timeline_path(@user) %>" class="onefive">
    <span id="followings-length">
      <%= @user.followings.size %>
    </span>명을 구독하고,
    <span id="followers-length">
      <%= @user.followers.size %>
    </span>명이 구독 중
  </a><br>
</div>

<div class="user_status">
  <%= @user.information %>
</div>

<div class="center">
  <% if user_signed_in? && current_user != @user %>
    <%= link_to (current_user.is_follower?(@user) ? '구독 취소' : '구독 하기'), toggle_follow_path(@user), method: :post, class: "btn indigo darken-4", id: 'follow', remote: true %>
  <% end %>
</div>

<div class="line">
  <hr width="40.625em" align="center" color="#0b1d7b" size="1">
</div>

<br>
<br><br>

<div id="posts">
  <%= render partial: "posts" %>
</div>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

<style>
p iframe {
  display: none;
}
p img {
  display: none;
}
</style>

app/views/timelines/profile.js.erb
$('#posts').append('<%= j render partial: "posts" %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/timelines/saves.html.erb
<div id="posts">
  <%= render partial: "posts" %>
</div>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

<style>
p iframe {
  display: none;
}
p img {
  display: none;
}
</style>

app/views/timelines/saves.js.erb
$('#posts').append('<%= j render partial: "posts" %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/timelines/subscribe.html.erb
<div class="profileimage center">
    <% if @user.thumbnail.present? %>
      <%= link_to image_tag(@user.thumbnail, class: "z-depth-3 circle tl-size"), profile_timeline_path(@user.id) %>
    <% else %>
      <img src="/people.jpg" class="tl-size circle">
    <% end %>
</div>

<div class="user_name">
  <%= @user.name %>
</div>

<div class="user_subscribe">
  <a href="<%= subscribe_timeline_path(@user) %>" class="onefive">
    <span id="followings-length">
      <%= @user.followings.size %>
    </span>명을 구독하고,
    <span id="followers-length">
      <%= @user.followers.size %>
    </span>명이 구독 중
  </a><br>
</div>

<div class="user_status">
  <%= @user.information %>
</div>

<div class="center">
  <% if user_signed_in? && current_user != @user %>
    <%= link_to (current_user.is_follower?(@user) ? '구독 취소' : '구독 하기'), toggle_follow_path(@user), method: :post, class: "btn indigo darken-4", id: 'follow', remote: true %>
  <% end %>
</div>

<div class="line">
  <hr width="40.625em" align="center" color="#0b1d7b" size="1">
</div>



<div id="whoSubscribe">
  <div>
    <div class="letSubscribe onefive"><%= @user.name %>님이 구독하는</div>
    <% if @user.followings.present? %>
      <% @user.followings.each do |following| %>
        <div class="subscribeImgWrite">
          <span class="subscribeImgMargin"> <!-- 이미지 -->
            <% if following.thumbnail.present? %>
              <%= link_to image_tag(following.thumbnail, class: "subscribeProfileImg circle"), profile_timeline_path(following) %>
            <% else %>
              <a href="<%= profile_timeline_path(following) %>"><img src="/people.jpg" class="subscribeProfileImg circle"></a>
            <% end %>
          </span>
          <div>
            <span class="subscribeProfileWrite">
              <div class="subscribeUser onefive"><%= following.name %></div><!-- 사람이름 -->
              <% if following.information.present? %>
                <div class="subscribeWrite">"<%= following.information %>"</div> <!-- 한줄 -->
              <% else %>
                <div class="grey-text" >"한 줄 없음"</div>
              <% end %>
            </span>
          </div>
      <% end %>
    <% else %>
      <p class="grey-text">"사람이 아직 없네요..."</p>
    <% end %>
      </div>
  </div>

  <div id="whomSubscribe">
    <div class="letSubscribe onefive"><%= @user.name %>님을 구독하는</div>
    <% if @user.followers.present? %>
      <% @user.followers.each do |follower| %>
        <div class="subscribeImgWrite">
          <span class="col">
            <% if follower.thumbnail.present? %>
              <%= link_to image_tag(follower.thumbnail, class: "subscribeProfileImg circle"), profile_timeline_path(follower) %>
            <% else %>
              <a href="<%= profile_timeline_path(follower) %>"><img src="/people.jpg" class="subscribeProfileImg circle"></a>
            <% end %>
          </span>
          <span class="subscribeProfileWrite">
            <div class="subscribeUser onefive"><%= follower.name %></div>
            <% if follower.information.present? %>
              <div class="subscribeWrite">"<%= follower.information %>"</div>
            <% else %>
              <div class="grey-text">"한 줄 없음"</div>
            <% end %>
          </span>
        </div>
      <% end %>
    <% else %>
      <p class="grey-text">"사람이 아직 없네요..."</p>
    <% end %>
    </div>


</div>

<%= render '/layouts/footer' %>

app/views/timelines/tag.html.erb
<div class="profileimage center">
    <% if @user.thumbnail.present? %>
      <%= link_to image_tag(@user.thumbnail, class: "z-depth-3 circle tl-size"), profile_timeline_path(@user.id) %>
    <% else %>
      <img src="/people.jpg" class="tl-size circle">
    <% end %>
</div>

<div class="user_name">
  <%= @user.name %>
</div>

<div class="user_subscribe">
  <a href="<%= subscribe_timeline_path(@user) %>" class="onefive"><span id="followings-length"><%= @user.followings.size %></span>명을 구독하고, <span id="followers-length"><%= @user.followers.size %></span>명이 구독 중</a><br>
</div>

<div class="user_status">
  <%= @user.information %>
</div>

<div class="center">
  <% if user_signed_in? && current_user != @user %>
    <%= link_to (current_user.is_follower?(@user) ? '구독 취소' : '구독 하기'), toggle_follow_path(@user), method: :post, class: "btn indigo darken-4", id: 'follow', remote: true %>
  <% end %>
</div>

<div class="line">
  <hr width="40.625em" align="center" color="#0b1d7b" size="1">
</div>

<br>
<br><br>

<div id="posts">
  <%= render partial: "posts" %>
</div>

<div id="infinite-posts">
  <%= will_paginate @posts %>
</div>

app/views/timelines/tag.js.erb
$('#posts').append('<%= j render partial: "posts" %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>