config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    post "/like", to:"likes#like_toggle", defaults: { format: 'js' }
    resources :comments, only: [:create, :destroy], defaults: { format: 'js' }
    collection do
      get :search, defaults: { format: 'js' }
      get :search_post, defaults: { format: 'js' }
      get :crop
    end
    member do
      get :autoinit, defaults: { format: 'js' }
      get :cancel, defaults: { format: 'js' }
      get :by_song
    end
  end
  resources :timelines, only: [:index] do
    collection do
      get :saves
    end
    member do
      get :profile
      get :subscribe
    end
  end
  resources :follows, only: [:create] do
    member do
      post :toggle, defaults: { format: 'js' }
    end
  end
  resources :alarms, only: [:index]
  resources :alarms, only: [:destroy], defaults: { format: 'js' }
  resources :subcomments, only: [:create, :destroy], defaults: { format: 'js' }

  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/copyurl/:id' => 'copys#copy', defaults: { format: 'js' }, :as => '/copyurl'
  get '/timelines/tag/:name' => 'timelines#tag'
  get '/check_identity/:identity' => 'checks#identity'
  get '/check_name/:name' => 'checks#name'
  get '/direct_music_search/:search_music' => 'posts#music_search'
  get '/direct_search_songs/:search_song' => 'posts#direct_search_songs'
  get '/direct_search_singers/:search_singer' => 'posts#direct_search_singers'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
 <div id="footer_made_row" class="container">
   <div class="row footer_made_row_flex">
     <div class="col l3 s12">
       <h5 class="white-text onefivetext">한 / 시 / 오 / 분</h5>
       <p class="grey-text text-lighten-4">음악은 기억과 함께.</p>
     </div>
     <div class="col l6 offset-l3 s12 onefivetext2">
       <h5 class="white-text">만든 이</h5>
       <ul>
         <li class="footer_made"><a class=" grey-text text-lighten-3" href="#!">기획 | 박현규 이지민</a></li>
         <li class="footer_made"><a class=" grey-text text-lighten-3" href="#!">개발 | 김은식 박현규 이우빈 이지민 이혜진 장성원</a></li>
         <li class="footer_made"><a class="grey-text text-lighten-3" href="#!">디자인 | 박현규</a></li>
       </ul>
     </div>
   </div>
 </div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>한/시/오/분</title>
  <link rel="shortcut icon" href="/favicon.ico">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= tinymce_assets %>
</head>
<body>

  <nav>
  <!-- 네브바 시작 -->
    <div class="nav-wrapper white navPage">
      <div class="logo onefive">
        <%= link_to '한 / 시 / 오 / 분', root_path, class: "brand-logo", id: :onefive %>
      </div>
      <% if controller.controller_name == "posts" && controller.action_name == "index" %>
        <div class="navCenterWrite onefive nav2">지금 이 글</div>
      <% elsif controller.controller_name == "timelines" && controller.action_name == "index" %>
        <div class="navCenterWrite onefive nav2">구독한 글</div>
      <% elsif controller.controller_name == "timelines" && controller.action_name == "saves" %>
        <div class="navCenterWrite onefive nav2">담은 글</div>
      <% end %>
     <!-- 상황에 맞게 페이지 이름 뜨도록 설정해주세요  -->

      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        <div class="p_icons">
          <!-- 검색기능 시작 -->
          <li><a class="modal-trigger" href="#modal1"><i class="material-icons onefive">search</i></a></li>
           <div id="modal1" class="modal">
            <div id="search123">
             <div id="search2"> <!--두번째 세션 탭 시작 -->
                <ul id ="search_hover" class="tabs">
                  <li class="tab session_active"><a class="active grey-text" href="#search_music" id="search-music">음악</a></li>
                  <li class="tab session1_li">|</li>
                  <li class="tab session_active"><a class="active grey-text" href="#search_user" id="search-user">사용자</a></a></li>
                  <li class="tab session1_li">|</li>
                  <li class="tab session_active"><a class="active grey-text" href="#search_article" id="search-post">글</a></li>
                </ul>
             </div> <!-- 탭 끝 -->
             <div id="search3"> <!-- 세번째 세션시작. 검색목록 나열 -->

               <div id="search_music" class="search_center_form"> <!-- 음악을 눌렀을 때 -->
                 <%= form_tag(search_post_posts_path, method: :get, remote: true) do %>
                   <span class="search_input"> <!--아이콘과 검색바 -->
                     <!--아이콘-->
                     <i class="large material-icons search_icon">search</i>
                     <!--검색-->
                     <div class="search_input_div"><input type="text" class="search_input_div_bar" name="search_music" ></div>
                   </span>
                 <% end %>
                 <div id="music-lists3">
                 </div>
               </div> <!-- 음악을 눌렀을 때 끝 -->

              <div id="search_user" class="search_center_form"> <!-- 사용자를 눌렀을때 -->
                <form action='<%= posts_path %>' method="GET">
                  <span class="search_input"> <!--아이콘과 검색바 -->
                    <!--아이콘-->
                    <i class="large material-icons search_icon">search</i>
                    <!--검색-->
                    <div class="search_input_div"><input type="text" class="search_input_div_bar" name="search_user" ></div>
                  </span>
                </form>
              </div> <!-- 사용자를 눌렀을때 끝 -->
              <div id="search_article" class="search_center_form"> <!-- 글을 눌렀을때 -->
                <div id=#search1> <!-- 첫번째 세션 -->
                  <form action='<%= posts_path %>' method="GET">
                    <span class="search_input"> <!--아이콘과 검색바 -->
                      <!--아이콘-->
                      <i class="large material-icons search_icon">search</i>
                      <!--검색-->
                      <div class="search_input_div"><input type="text" class="search_input_div_bar" name="search" ></div>
                    </span>
                  </form>
                </div> <!-- 첫 세션끝 -->
              </div> <!-- 글을 눌럿을 때 끝 -->
             </div> <!--세번째 세션 끝 -->
            </div>
          </div>
            <!-- 검색기능 끝 -->
          <li><a href="#" id="navbarCssRight" data-target="slide-out" class="sidenav-trigger show-on-large onefive"><i class="material-icons">menu</i></a></li>
        </div>
        <% else %>
        <li><%= link_to '로그인', new_user_session_path, class: "onefive" %></li>
        <li><%= link_to '회원가입', new_user_registration_path, class: "onefive" %></li>
        <% end %>
      </ul>
    </div>
    </div>
  </nav>

  <% flash.each do |message_type, message| %>
    <script type="text/javascript">
      var toastHTML= "<%= message %>"
      M.toast({html: toastHTML});
    </script>
    <!-- <%= message %> -->
  <% end %>

  <!-- 오른쪽에서 나오는 navbar -->
  <% if user_signed_in? %>
  <ul id="slide-out" class="sidenav">
    <div class="sidenav_flex">
      <div class="sidenav_border"></div>
      <div class="user-view">
        <div class="sidenav_profileimg center">
          <% if current_user.thumbnail.present? %>
            <%= link_to image_tag(current_user.thumbnail, class: "z-depth-3 circle tl-size"), profile_timeline_path(current_user) %>
          <% else %>
            <img src="/people.jpg" class="tl-size circle">
          <% end %>
        </div>
        <div class="sidenav_user_name center">
          <%= link_to "#{current_user.name}", profile_timeline_path(current_user), class: :onefive %>
          <%= link_to 'settings', edit_user_registration_path, class: "onefive material-icons", id: "sidenav_setting"%>
        </div>
        <div class="sidenav_user_subscribe center">
          <a href="<%= subscribe_timeline_path(current_user) %>" class="onefive"><span id="followings-size"><%= current_user.followings.size %></span>명을 구독하고, <span id="followers-size"><%= current_user.followers.size %></span>명이 구독 중</a>
        </div>
      </div>
      <div class="sidenav_links center">
        <div class="sidenav_links_one"><%= link_to '구독한 글', timelines_path, class: :onefive %></div><!-- 구독 주소 넣어주세요 -->
        <div class="sidenav_links_one"><%= link_to '지금 이 글', root_path, class: :onefive %></div><!-- 지금 이 글 주소 넣어주세요 -->
        <div class="sidenav_links_one"><%= link_to '담은 글', saves_timelines_path, class: :onefive %></div><!-- 담은 글 주소 넣어주세요 -->
        <div class="sidenav_links_one"><%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: :onefive %></div>
      </div>
      <div class="sidenav_notice_title center">
        <%= link_to '소식', '#', class: :onefive %>(<%= current_user.alarms.size %>)
      </div>
      <div class="sidenav_line">
        <hr width="200px" align="center" color="#8b8b8b" size="1">
      </div>
       <!-- 사이드네브에서 알림뜨는거임 -->
     <div class="sidenav_notice">
       <% if current_user.alarms.present? %>
         <% current_user.alarms.each do |alarm| %>
           <div class="sidenav_notice_profileimg" id="alarm-<%= alarm.id %>"> <!-- 프로필 이미지 -->
             <% if alarm.find_from_who.try("thumbnail").present? %>
               <%= link_to image_tag(alarm.find_from_who.thumbnail, class: "circle sidenav_notice_profileimg_size"), profile_timeline_path(alarm.find_from_who) %>
             <% else %>
               <img src="/people.jpg" class="tl-size circle sidenav_notice_profileimg_size">
             <% end %>
           </div>
            <div class="sidenav_notice_text" id="alarm2-<%= alarm.id %>">
              <% if alarm.like? %>
                <div id="navSmallRightExceptImg">
                 <div id="navSmallRight">
                   <div class="sidenav_notice_text_about">
                     <a class="onefive" href="<%= profile_timeline_path(alarm.findable_id) %>">[ <%= alarm.content %> ] 님이 회원님의 글을 저장 하셨습니다.</a>
                   </div>
                   <div class="sidenav_notice_text_ago">
                     <%= time_ago_in_words alarm.created_at %> 전
                   </div>
                 </div>
                 <div class="sidenav_notice_delete">
                   <%= link_to 'close', alarm_path(alarm), method: :delete, class: "material-icons tiny black-text", remote: true %>
                 </div>
               </div>
             <% elsif alarm.comment? %>
               <div id="navSmallRightExceptImg">
                <div id="navSmallRight">
                  <div class="sidenav_notice_text_about">
                    <a class="onefive" href="<%= post_path(alarm.findable_id) %>">[ <%= alarm.content %> ] 님이 회원님의 글에 댓글을 달았습니다.</a>
                  </div>
                  <div class="sidenav_notice_text_ago">
                    <%= time_ago_in_words alarm.created_at %> 전
                  </div>
                </div>
                <div class="sidenav_notice_delete">
                  <%= link_to 'close', alarm_path(alarm), method: :delete, class: "material-icons tiny black-text", remote: true %>
                </div>
              </div>
              <% elsif alarm.follow? %>
                <div id="navSmallRightExceptImg">
                 <div id="navSmallRight">
                   <div class="sidenav_notice_text_about">
                     <a class="onefive" href="<%= profile_timeline_path(alarm.findable_id) %>">[ <%= alarm.content %> ] 님이 회원님을 구독하셨습니다.</a>
                   </div>
                   <div class="sidenav_notice_text_ago">
                     <%= time_ago_in_words alarm.created_at %> 전
                   </div>
                 </div>
                 <div class="sidenav_notice_delete">
                   <%= link_to 'close', alarm_path(alarm), method: :delete, class: "material-icons tiny black-text", remote: true %>
                 </div>
               </div>
               <% elsif alarm.tag? %>
                 <div id="navSmallRightExceptImg">
                  <div id="navSmallRight">
                    <div class="sidenav_notice_text_about">
                      <a class="onefive" href="<%= post_path(alarm.findable_id) %>">[ <%= alarm.content %> ] 님이 회원님을 태그하셨습니다.</a>
                    </div>
                    <div class="sidenav_notice_text_ago">
                      <%= time_ago_in_words alarm.created_at %> 전
                    </div>
                  </div>
                  <div class="sidenav_notice_delete">
                    <%= link_to 'close', alarm_path(alarm), method: :delete, class: "material-icons tiny black-text", remote: true %>
                  </div>
                </div>
                <% elsif alarm.subcomment? %>
                  <div id="navSmallRightExceptImg">
                   <div id="navSmallRight">
                     <div class="sidenav_notice_text_about">
                       <a class="onefive" href="<%= post_path(alarm.findable_id) %>">[ <%= alarm.content %> ] 님이 회원님의 댓글에 대댓글을 달았습니다.</a>
                     </div>
                     <div class="sidenav_notice_text_ago">
                       <%= time_ago_in_words alarm.created_at %> 전
                     </div>
                   </div>
                   <div class="sidenav_notice_delete">
                     <%= link_to 'close', alarm_path(alarm), method: :delete, class: "material-icons tiny black-text", remote: true %>
                   </div>
                 </div>
             <% end %>
           </div>
           <% end %>
         <!--소식넣어주세요(은식이가 댓글 짠 레이아웃 그대로 긁어올 예정-->
       <% end %>
     </div>
    </div>
  </ul>
  <% end %>
  <!-- 오른쪽에서 나오는 navbar 끝 -->

  <%= yield %>


</body>
</html>

<script>
  $('.dropdown-trigger').dropdown();

  function music_direct_search(search_music){
    $.get("/direct_music_search/" + search_music, function(data){
    });
  }

  $('input.search_input_div_bar').on('keyup', function(){
    var val = this.value;
    music_direct_search(val);
  });

</script>